### ISSUE TITLE
Linking the POI on a map

### ISSUE THREAD

**Issue by Maryjezek** [Maryjezek/travel-optimizer#11]
If possible - find a map that allows PINS for about 20 point of interest

**Comment by Olopez92084** [comment]
Added an interactive custom map from Mapbox. This API is free, unlike google maps. I set it up to display historic sites, food and lodging, etc... in satellite view style. If the user clicks the location button, it will get the users location and they can scan POI's nearby. I still haven't been able to figure out any way of linking the results from the above searched cities, to be able to automatically show on that map though. Perhaps with more work, I can figure it out. 

Still digging through the site to see if there are any other modifications that can be added to the map. 

https://docs.mapbox.com/mapbox-gl-js/api/map/
